baseURL = '/'
languageCode = 'en-us'
title = 'Tooabstractive'

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true

paginate = 10

################################# Default parameters ##########################


[params]

  author = "Mohammad Jamiu"
  og_image = "/images/tabluelogopng.png"
 
[params.social.share]
    facebook = true
    pinterest = true
    twitter = true
    whatsapp = true
    email = true

[build.environment]
    TZ = "Africa/Lagos"
  
[markup]
    [markup.goldmark.renderer]
        unsafe=true

[menu]
    [[menu.main]]
        name = "Home &#127968;"
        url = "/"
        weight = 1
 
    [[menu.main]]
        name = "Posts &#128221;"
        url = "/posts/"
        weight = 2
    [[menu.main]]
        name = "Circuit Analysis"
        url = "/learnca/"
        weight = 3
    [[menu.main]]
        name = "Ebooks &#128218;"
        url = "/ebooks/"
        weight = 4
    [[menu.main]]
        name = "Contact &#9742;"
        url = "/contact/"
        weight = 5
  
    [[menu.main]]
        name = "About &#8505;"
        url = "/about/"
        weight = 6

    [[menu.main]]
        name = "Write For Us &#9997;"
        url = "/about/#write"
        weight = 7


[related]
    threshold = 0
    includeNewer = true
    toLower = false

    [[related.indices]]
        name= "categories"
        weight = 100

    [[related.indices]]
        name= "date"
        weight = 10


[taxonomies]
    category = "categories"
    ebookcategory = "ebookcategories"